# Generated by Django 6.0.2 on 2026-02-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GARAGE_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('slot not available', 'Slot Not Available')], default='pending', max_length=20),
        ),
    ]
